name: Email Step Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f2000516@ds.study.iitm.ac.in
        run: echo "Hello, world!"
